/// © Tobias Sachs
/// Colors/KnownColors.cs
/// 22.01.2023

using System.ComponentModel;

namespace tcs.Colors;

// Equivalent to WPF, WinForms, HTML and CSS Colors
[Description("Known Colors")]
public sealed class KnownColors : ColorNameEnumerator
{
    public static ColorName AliceBlue { get => new("Alice Blue", new ColorCode(240, 248, 255), ""); }
    public static ColorName AntiqueWhite { get => new("Antique White", new ColorCode(250, 235, 215), ""); }
    public static ColorName Aqua { get => new("Aqua", new ColorCode(0, 255, 255), ""); }
    public static ColorName Aquamarine { get => new("Aquamarine", new ColorCode(127, 255, 212), ""); }
    public static ColorName Azure { get => new("Azure", new ColorCode(240, 255, 255), ""); }
    public static ColorName Beige { get => new("Beige", new ColorCode(245, 245, 220), ""); }
    public static ColorName Bisque { get => new("Bisque", new ColorCode(255, 228, 196), ""); }
    public static ColorName Black { get => new("Black", new ColorCode(0, 0, 0), ""); }
    public static ColorName BlanchedAlmond { get => new("Blanched Almond", new ColorCode(255, 235, 205), ""); }
    public static ColorName Blue { get => new("Blue", new ColorCode(0, 0, 255), ""); }
    public static ColorName BlueViolet { get => new("Blue Violet", new ColorCode(138, 43, 226), ""); }
    public static ColorName Brown { get => new("Brown", new ColorCode(165, 42, 42), ""); }
    public static ColorName BurlyWood { get => new("Burly Wood", new ColorCode(222, 184, 135), ""); }
    public static ColorName CadetBlue { get => new("Cadet Blue", new ColorCode(95, 158, 160), ""); }
    public static ColorName Chartreuse { get => new("Chartreuse", new ColorCode(127, 255, 0), ""); }
    public static ColorName Chocolate { get => new("Chocolate", new ColorCode(210, 105, 30), ""); }
    public static ColorName Coral { get => new("Coral", new ColorCode(255, 127, 80), ""); }
    public static ColorName CornflowerBlue { get => new("Cornflower Blue", new ColorCode(100, 149, 237), ""); }
    public static ColorName Cornsilk { get => new("Cornsilk", new ColorCode(255, 248, 220), ""); }
    public static ColorName Crimson { get => new("Crimson", new ColorCode(220, 20, 60), ""); }
    public static ColorName Cyan { get => new("Cyan", new ColorCode(0, 255, 255), ""); }
    public static ColorName DarkBlue { get => new("Dark Blue", new ColorCode(0, 0, 139), ""); }
    public static ColorName DarkCyan { get => new("Dark Cyan", new ColorCode(0, 139, 139), ""); }
    public static ColorName DarkGoldenrod { get => new("Dark Goldenrod", new ColorCode(184, 134, 11), ""); }
    public static ColorName DarkGray { get => new("Dark Gray", new ColorCode(169, 169, 169), ""); }
    public static ColorName DarkGreen { get => new("Dark Green", new ColorCode(0, 100, 0), ""); }
    public static ColorName DarkKhaki { get => new("Dark Khaki", new ColorCode(189, 183, 107), ""); }
    public static ColorName DarkMagenta { get => new("Dark Magenta", new ColorCode(139, 0, 139), ""); }
    public static ColorName DarkOliveGreen { get => new("Dark Olive Green", new ColorCode(85, 107, 47), ""); }
    public static ColorName DarkOrange { get => new("Dark Orange", new ColorCode(255, 140, 0), ""); }
    public static ColorName DarkOrchid { get => new("Dark Orchid", new ColorCode(153, 50, 204), ""); }
    public static ColorName DarkRed { get => new("Dark Red", new ColorCode(139, 0, 0), ""); }
    public static ColorName DarkSalmon { get => new("Dark Salmon", new ColorCode(233, 150, 122), ""); }
    public static ColorName DarkSeaGreen { get => new("Dark Sea Green", new ColorCode(143, 188, 143), ""); }
    public static ColorName DarkSlateBlue { get => new("Dark Slate Blue", new ColorCode(72, 61, 139), ""); }
    public static ColorName DarkSlateGray { get => new("Dark Slate Gray", new ColorCode(47, 79, 79), ""); }
    public static ColorName DarkTurquoise { get => new("Dark Turquoise", new ColorCode(0, 206, 209), ""); }
    public static ColorName DarkViolet { get => new("Dark Violet", new ColorCode(148, 0, 211), ""); }
    public static ColorName DeepPink { get => new("Deep Pink", new ColorCode(255, 20, 147), ""); }
    public static ColorName DeepSkyBlue { get => new("Deep Sky Blue", new ColorCode(0, 191, 255), ""); }
    public static ColorName DimGray { get => new("Dim Gray", new ColorCode(105, 105, 105), ""); }
    public static ColorName DodgerBlue { get => new("Dodger Blue", new ColorCode(30, 144, 255), ""); }
    public static ColorName Firebrick { get => new("Firebrick", new ColorCode(178, 34, 34), ""); }
    public static ColorName FloralWhite { get => new("Floral White", new ColorCode(255, 250, 240), ""); }
    public static ColorName ForestGreen { get => new("Forest Green", new ColorCode(34, 139, 34), ""); }
    public static ColorName Fuchsia { get => new("Fuchsia", new ColorCode(255, 0, 255), ""); }
    public static ColorName Gainsboro { get => new("Gainsboro", new ColorCode(220, 220, 220), ""); }
    public static ColorName GhostWhite { get => new("Ghost White", new ColorCode(248, 248, 255), ""); }
    public static ColorName Gold { get => new("Gold", new ColorCode(255, 215, 0), ""); }
    public static ColorName Goldenrod { get => new("Goldenrod", new ColorCode(218, 165, 32), ""); }
    public static ColorName Gray { get => new("Gray", new ColorCode(128, 128, 128), ""); }
    public static ColorName Green { get => new("Green", new ColorCode(0, 128, 0), ""); }
    public static ColorName GreenYellow { get => new("Green Yellow", new ColorCode(173, 255, 47), ""); }
    public static ColorName Honeydew { get => new("Honeydew", new ColorCode(240, 255, 240), ""); }
    public static ColorName HotPink { get => new("Hot Pink", new ColorCode(255, 105, 180), ""); }
    public static ColorName IndianRed { get => new("Indian Red", new ColorCode(205, 92, 92), ""); }
    public static ColorName Indigo { get => new("Indigo", new ColorCode(75, 0, 130), ""); }
    public static ColorName Ivory { get => new("Ivory", new ColorCode(255, 255, 240), ""); }
    public static ColorName Khaki { get => new("Khaki", new ColorCode(240, 230, 140), ""); }
    public static ColorName Lavender { get => new("Lavender", new ColorCode(230, 230, 250), ""); }
    public static ColorName LavenderBlush { get => new("Lavender Blush", new ColorCode(255, 240, 245), ""); }
    public static ColorName LawnGreen { get => new("Lawn Green", new ColorCode(124, 252, 0), ""); }
    public static ColorName LemonChiffon { get => new("Lemon Chiffon", new ColorCode(255, 250, 205), ""); }
    public static ColorName LightBlue { get => new("Light Blue", new ColorCode(173, 216, 230), ""); }
    public static ColorName LightCoral { get => new("Light Coral", new ColorCode(240, 128, 128), ""); }
    public static ColorName LightCyan { get => new("Light Cyan", new ColorCode(224, 255, 255), ""); }
    public static ColorName LightGoldenrodYellow { get => new("Light Goldenrod Yellow", new ColorCode(250, 250, 210), ""); }
    public static ColorName LightGray { get => new("Light Gray", new ColorCode(211, 211, 211), ""); }
    public static ColorName LightGreen { get => new("Light Green", new ColorCode(144, 238, 144), ""); }
    public static ColorName LightPink { get => new("Light Pink", new ColorCode(255, 182, 193), ""); }
    public static ColorName LightSalmon { get => new("Light Salmon", new ColorCode(255, 160, 122), ""); }
    public static ColorName LightSeaGreen { get => new("Light Sea Green", new ColorCode(32, 178, 170), ""); }
    public static ColorName LightSkyBlue { get => new("Light Sky Blue", new ColorCode(135, 206, 250), ""); }
    public static ColorName LightSlateGray { get => new("Light Slate Gray", new ColorCode(119, 136, 153), ""); }
    public static ColorName LightSteelBlue { get => new("Light Steel Blue", new ColorCode(176, 196, 222), ""); }
    public static ColorName LightYellow { get => new("Light Yellow", new ColorCode(255, 255, 224), ""); }
    public static ColorName Lime { get => new("Lime", new ColorCode(0, 255, 0), ""); }
    public static ColorName LimeGreen { get => new("Lime Green", new ColorCode(50, 205, 50), ""); }
    public static ColorName Linen { get => new("Linen", new ColorCode(250, 240, 230), ""); }
    public static ColorName Magenta { get => new("Magenta", new ColorCode(255, 0, 255), ""); }
    public static ColorName Maroon { get => new("Maroon", new ColorCode(128, 0, 0), ""); }
    public static ColorName MediumAquamarine { get => new("Medium Aquamarine", new ColorCode(102, 205, 170), ""); }
    public static ColorName MediumBlue { get => new("Medium Blue", new ColorCode(0, 0, 205), ""); }
    public static ColorName MediumOrchid { get => new("Medium Orchid", new ColorCode(186, 85, 211), ""); }
    public static ColorName MediumPurple { get => new("Medium Purple", new ColorCode(147, 112, 219), ""); }
    public static ColorName MediumSeaGreen { get => new("Medium Sea Green", new ColorCode(60, 179, 113), ""); }
    public static ColorName MediumSlateBlue { get => new("Medium Slate Blue", new ColorCode(123, 104, 238), ""); }
    public static ColorName MediumSpringGreen { get => new("Medium Spring Green", new ColorCode(0, 250, 154), ""); }
    public static ColorName MediumTurquoise { get => new("Medium Turquoise", new ColorCode(72, 209, 204), ""); }
    public static ColorName MediumVioletRed { get => new("Medium VioletRed", new ColorCode(199, 21, 133), ""); }
    public static ColorName MidnightBlue { get => new("Midnight Blue", new ColorCode(25, 25, 112), ""); }
    public static ColorName MintCream { get => new("Mint Cream", new ColorCode(245, 255, 250), ""); }
    public static ColorName MistyRose { get => new("Misty Rose", new ColorCode(255, 228, 225), ""); }
    public static ColorName Moccasin { get => new("Moccasin", new ColorCode(255, 228, 181), ""); }
    public static ColorName NavajoWhite { get => new("Navajo White", new ColorCode(255, 222, 173), ""); }
    public static ColorName Navy { get => new("Navy", new ColorCode(0, 0, 128), ""); }
    public static ColorName OldLace { get => new("Old Lace", new ColorCode(253, 245, 230), ""); }
    public static ColorName Olive { get => new("Olive", new ColorCode(128, 128, 0), ""); }
    public static ColorName OliveDrab { get => new("Olive Drab", new ColorCode(107, 142, 35), ""); }
    public static ColorName Orange { get => new("Orange", new ColorCode(255, 165, 0), ""); }
    public static ColorName OrangeRed { get => new("Orange Red", new ColorCode(255, 69, 0), ""); }
    public static ColorName Orchid { get => new("Orchid", new ColorCode(218, 112, 214), ""); }
    public static ColorName PaleGoldenrod { get => new("Pale Goldenrod", new ColorCode(238, 232, 170), ""); }
    public static ColorName PaleGreen { get => new("Pale Green", new ColorCode(152, 251, 152), ""); }
    public static ColorName PaleTurquoise { get => new("Pale Turquoise", new ColorCode(175, 238, 238), ""); }
    public static ColorName PaleVioletRed { get => new("Pale Violet Red", new ColorCode(219, 112, 147), ""); }
    public static ColorName PapayaWhip { get => new("Papaya Whip", new ColorCode(255, 239, 213), ""); }
    public static ColorName PeachPuff { get => new("Peach Puff", new ColorCode(255, 218, 185), ""); }
    public static ColorName Peru { get => new("Peru", new ColorCode(205, 133, 63), ""); }
    public static ColorName Pink { get => new("Pink", new ColorCode(255, 192, 203), ""); }
    public static ColorName Plum { get => new("Plum", new ColorCode(221, 160, 221), ""); }
    public static ColorName PowderBlue { get => new("Powder Blue", new ColorCode(176, 224, 230), ""); }
    public static ColorName Purple { get => new("Purple", new ColorCode(128, 0, 128), ""); }
    public static ColorName Red { get => new("Red", new ColorCode(255, 0, 0), ""); }
    public static ColorName RosyBrown { get => new("Rosy Brown", new ColorCode(188, 143, 143), ""); }
    public static ColorName RoyalBlue { get => new("Royal Blue", new ColorCode(65, 105, 225), ""); }
    public static ColorName SaddleBrown { get => new("Saddle Brown", new ColorCode(139, 69, 19), ""); }
    public static ColorName Salmon { get => new("Salmon", new ColorCode(250, 128, 114), ""); }
    public static ColorName SandyBrown { get => new("Sandy Brown", new ColorCode(244, 164, 96), ""); }
    public static ColorName SeaGreen { get => new("Sea Green", new ColorCode(46, 139, 87), ""); }
    public static ColorName SeaShell { get => new("Sea Shell", new ColorCode(255, 245, 238), ""); }
    public static ColorName Sienna { get => new("Sienna", new ColorCode(160, 82, 45), ""); }
    public static ColorName Silver { get => new("Silver", new ColorCode(192, 192, 192), ""); }
    public static ColorName SkyBlue { get => new("Sky Blue", new ColorCode(135, 206, 235), ""); }
    public static ColorName SlateBlue { get => new("Slate Blue", new ColorCode(106, 90, 205), ""); }
    public static ColorName SlateGray { get => new("Slate Gray", new ColorCode(112, 128, 144), ""); }
    public static ColorName Snow { get => new("Snow", new ColorCode(255, 250, 250), ""); }
    public static ColorName SpringGreen { get => new("Spring Green", new ColorCode(0, 255, 127), ""); }
    public static ColorName SteelBlue { get => new("Steel Blue", new ColorCode(70, 130, 180), ""); }
    public static ColorName Tan { get => new("Tan", new ColorCode(210, 180, 140), ""); }
    public static ColorName Teal { get => new("Teal", new ColorCode(0, 128, 128), ""); }
    public static ColorName Thistle { get => new("Thistle", new ColorCode(216, 191, 216), ""); }
    public static ColorName Tomato { get => new("Tomato", new ColorCode(255, 99, 71), ""); }
    public static ColorName Transparent { get => new("Transparent", new ColorCode(0, 0, 0, 0), ""); }
    public static ColorName Turquoise { get => new("Turquoise", new ColorCode(64, 224, 208), ""); }
    public static ColorName Violet { get => new("Violet", new ColorCode(238, 130, 238), ""); }
    public static ColorName Wheat { get => new("Wheat", new ColorCode(245, 222, 179), ""); }
    public static ColorName White { get => new("White", new ColorCode(255, 255, 255), ""); }
    public static ColorName WhiteSmoke { get => new("White Smoke", new ColorCode(245, 245, 245), ""); }
    public static ColorName Yellow { get => new("Yellow", new ColorCode(255, 255, 0), ""); }
    public static ColorName YellowGreen { get => new("Yellow Green", new ColorCode(154, 205, 50), ""); }
}
